[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/api/v1/heartbeat"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Environment-specific configurations
[environments.production]
name = "bmad-chromadb-production"

[environments.staging]
name = "bmad-chromadb-staging"

# Volume configuration for persistent storage
[volumes]
chroma_data = "/chroma/chroma"